# Generated by Django 5.1.1 on 2024-09-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_name', models.CharField(max_length=300)),
                ('per_image', models.ImageField(default='', upload_to='')),
                ('per_number', models.IntegerField(default=0)),
                ('per_short_dis', models.CharField(max_length=300)),
                ('per_long_dis', models.CharField(max_length=500)),
                ('per_email', models.EmailField(blank=True, max_length=254)),
                ('per_slug', models.SlugField(blank=True, default='')),
            ],
        ),
    ]
