# Generated by Django 5.1.1 on 2024-09-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_image', models.ImageField(default='media/img/course/01.png', upload_to='')),
                ('title', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=300)),
                ('days', models.IntegerField(default=0)),
                ('desk', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=1000)),
                ('course_time', models.IntegerField(default=0)),
                ('total_speak', models.IntegerField(default=0)),
                ('total_std', models.IntegerField(default=0)),
                ('certificate', models.BooleanField(default=True)),
                ('price', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
    ]
