# Generated by Django 5.1.1 on 2024-09-29 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog_detail', '0001_initial'),
        ('programs', '0005_alter_programs_protime'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_detail',
            name='program',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='programs.programs'),
        ),
    ]
