# Generated by Django 5.1.1 on 2024-09-29 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prog_detail', '0002_program_detail_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program_detail',
            name='slug',
        ),
    ]
