# Generated by Django 5.1.1 on 2024-09-29 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog_detail', '0003_remove_program_detail_slug'),
        ('programs', '0005_alter_programs_protime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program_detail',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='programs.programs'),
        ),
    ]
