# Generated by Django 5.1.1 on 2024-09-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protitle', models.CharField(max_length=300)),
                ('proshortdescription', models.CharField(max_length=300)),
                ('proprice', models.IntegerField(default=0)),
                ('proimage', models.IntegerField(default='')),
                ('prodescription', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, default='', editable=False)),
            ],
        ),
    ]
