# Generated by Django 5.1.1 on 2024-09-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_programs_proimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='protime',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='programs',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
