# Generated by Django 5.1.1 on 2024-09-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_programs_protime_alter_programs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='protime',
            field=models.CharField(default=0, max_length=300),
        ),
    ]
